### ISSUE TITLE
Implement classic hyperlinks.

### ISSUE THREAD

**Issue by michael** [substance/lens#32]

**Comment by augbog** [comment]
Hey I was hoping to contribute and tried working on this issue but it seems this may require changes in substance or ui repo? I was hoping to simply copy the functionality of the [link.js](https://github.com/substance/substance/blob/master/document/nodes/link.js) which is inherited from `Document` like how Emphasis and Strong are inherited. I was able to add the tool component to content_toolbar.js and then enable it in the `ENABLED_TOOLS` in content_editor.js. However it seems the styles are not available at least not in how they are being referenced right now.

For example, the [prose-editor](http://substance.io/demos/prose-editor/) demo uses the link tool and it seems to be grabbing its styles from [writer.scss](https://github.com/substance/substance/blob/master/ui/styles/writer.scss) under the substance/ui folder where it imports [link.scss](https://github.com/substance/substance/blob/master/ui/styles/modules/link.scss). 

However in the lens-writer app, it seems to be referencing the styles from the ui repo where it has its own [writer.scss](https://github.com/substance/ui/blob/master/writer/writer.scss) file that does not include the link styles.

It seems the package.json is referencing an old version of substance which does not have the bundled ui folder which is why they are treated separately

```
 "substance": "substance/substance-legacy#193d87259fae45a0f546bdb133a9fc7f34d87b52",
 "substance-ui": "substance/ui#7a6cb53b1d6a1e55fa022c2b69a1b8f938f5ae4f"
```

Is there a reason why lens-writer is referencing older versions of the packages and why it would need these packages separated? Just curious :) this is an awesome project!

**Comment by obuchtala** [comment]
Lens-writer is in a prototype state. After this we took the lessons learned and tried to make substance better. Now the step back is missing, i.e., bringing lens-writer back on the substance main track.
However, good news, we are working on that the next weeks. So likely by end of this month this is done.

**Comment by augbog** [comment]
@oliver---- Ah gotcha. Sorry didn't realize. Looking forward to the final result :)

**Comment by obuchtala** [comment]
Cool you like it. I ping you when it is done :)

**Comment by michael** [comment]
@augbog This is fixed now. You can run the latest dev version by checking out the #edge branch. However, still don't expect it to be stable.
